version: '2.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./node_modules/serve/bin/serve.js -s build
    entrypoint: /docker-entrypoint.sh
    ports:
      - "127.0.0.1:8098:5000"
    volumes:
      - node_modules:/usr/src/app/node_modules
      - /etc/localtime:/etc/localtime:ro

volumes:
  node_modules:
